name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
      tlint:
        name: TLint

        continue-on-error: false

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer install --no-interaction --no-suggest --ignore-platform-reqs

            - name: Run Tlint
              run: vendor/bin/tlint